version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - INSTALL_XDEBUG=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=9003
    volumes:
      - .:/var/www
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: employee
      MYSQL_USER: local
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql-data:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
